### ISSUE TITLE
Add homebrew support

### ISSUE THREAD

**Issue by kgadek** [gnebbia/kb#17]
Loosely related to #15. 

I've created Homebrew tap with `kb` formula. I'd be happy to transfer this file (or even repo since there's only `kb.rb` there now) to you if you want. For now, with no `pip` package, it takes package from a repo.

Repo url: https://github.com/kgadek/homebrew-tools

Installation procedure using repo (tested on macOS):

```sh
brew tap kgadek/tools
brew install kgadek/tools/kb
```

Note: I'm definitely not an expert in Homebrew. It seems to work but definitely could get improvements. E.g. it doesn't pass `brew audit` ("1: col 1: Missing frozen string literal comment").

**Comment by gnebbia** [comment]
Thanks a lot Sir, could you please please investigate this brew audit error? It would better to fix it.
It would be nice to open a pull request to add this.
Actually since I don't know much about brew, I even have no idea on how to publish this for brew.

If you help me I can add you to the list of contributors!
Thanks again!

**Comment by kgadek** [comment]
Comparing original proposal to #25:

1. Instead of having separate repo, this will host the brew formula in this repo itself. The commands slightly change — `brew tap` will require two arguments, but that's a small price.
  In future it could be considered to make a PR to Homebrew-core with this, but this repo/project is too fresh for that now.
2. Fixed brew-audit errors.
3. Pinned repo clone to v0.1.2.

**Comment by gnebbia** [comment]
Thanks @kgadek that's awesome! I am closing this issue!
